# Default values for activiti-cloud-query-graphql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

graphql-query:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent

graphql-notifications:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent

graphql-subscriptions:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
